cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_book_num>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_book_num>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_book_num>/',views.full_remove, name='full_remove'),
]

dbprj_book/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('accounts/',include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('order/',include('order.urls')),
]

order/urls.py
from django.urls import path
from .views import *

app_name = 'orders'

urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('create_ajax/', OrderCreateAjaxView.as_view(),name='order_create_ajax'),
    path('checkout/', OrderCheckoutAjaxView.as_view(),name='order_checkout'),
    path('validation/', OrderImpAjaxView.as_view(),name='order_validation'),
    path('complete/', order_complete,name='order_complete'),
    
]

cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

# Create your models here.

class Cart(models.Model):
    objects = models.Manager()
    cart_id = models.CharField(max_length=250,primary_key=True)
    date_added = models.DateField(auto_now_add=True)
    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    objects = models.Manager()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.book_price * self.quantity

    def __str__(self):
        return str(self.product)
        

cart/views.py
from django.shortcuts import render,redirect, get_object_or_404
from shop.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request,product_book_num):
    product = Product.objects.get(book_num = product_book_num)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(

            cart_id = _cart_id(request)
        )
        cart.save()

    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.book_stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product = product,
            quantity = 1,
            cart = cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_item_find(request, total=0, counter=0, cart_item=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart)
        for cart_item in cart_items:
            total += (cart_item.product.book_price * cart_item.quantity)
            counter += cart_item.quantity
            yield cart_item 
    except ObjectDoesNotExist:
        pass

def cart_detail(request, total=0, counter=0, cart_item=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart)
        for cart_item in cart_items:
            total += (cart_item.product.book_price * cart_item.quantity)
            counter += cart_item.quantity
            
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart/cart.html', dict(cart_items=cart_items, total=total, counter=counter))

def cart_remove(request, product_book_num):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, book_num=product_book_num)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request, product_book_num):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, book_num=product_book_num)
    cart_item = CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

cart/templates/cart/cart.html
{% extends 'base.html' %}
{% block title %}- 장바구니{% endblock %}

{% block content %}
    {% if not cart_items %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">
                    장바구니가 비어있습니다.
                </h1>
                <br>
                <p class="text-center">
                    메인으로 돌아가 쇼핑을 해주세요
                </p>
                <br>
                <a href="/">메인으로</a>
            </div>
        </div>
    {% else %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">
                    장바구니
                </h1>
                <br>
            </div>
        </div>
        <div class="row mx-auto">
            <div class="col-12 col-12 col-md-12 col-lg-6 text-center">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th colspan="5">
                                내 장바구니
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for cart_item in cart_items %}
                            <tr>
                                <td>
                                    <a href="{{cart_item.product.get_absolute_url}}"> <img src="{{cart_item.product.image.url}}"
                                        alt="" class = "float-left rounded" width="100" height="100"></a>
                                </td>
                                <td>
                                    {{cart_item.product.book_name}}
                                    <br>
                                    책 번호: {{cart_item.product.book_num}}
                                    <br>
                                    가격: {{cart_item.product.book_price}}
                                    <br>
                                    총 : {{cart_item.quantity}} x {{cart_item.product.book_price}}
                                </td>
                                <td>
                                    {{cart_item.sub_total}} 원
                                </td>
                                {% if cart_item.quantity < cart_item.product.book_stock %}
                                    <td>
                                        <a href="{% url 'cart:add_cart' cart_item.product.book_num %}">
                                            <i class="fas fa-plus-circle" style='color:darkgray'></i></a>&nbsp;
                                        <a href="{% url 'cart:cart_remove' cart_item.product.book_num %}">
                                            <i class="fas fa-minus-circle" style='color:darkgray'></i></a>&nbsp;
                                        <a href="{% url 'cart:full_remove' cart_item.product.book_num %}">
                                            <i class="fas fa-trash" style='color:darkgray'></i></a>
                                    </td>
                                {% else %}
                                    <td>
                                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.book_num %}">
                                            <i class="fas fa-minus-circle" style='color:darkgray'></i></a>&nbsp;
                                        <a href="{% url 'cart:full_remove' cart_item.product.book_num %}">
                                            <i class="fas fa-trash" style='color:darkgray'></i></a>
                                    </td>
                                    <td></td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <table class="table">
                    <thread>
                        <tr>
                            <th>
                                결제 확인
                            </th>
                        </tr>
                    </thread>
                    <tbody>
                        <tr>
                            <td>
                            주문 사항을 확인하세요 !
                            </td>
                        </tr>
                        <tr>
                            <td class="text-left">
                                    총 금액 : <strong>{{ total }} 원</strong>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <div class="mx-auto">
                    <a href="{% url "orders:order_create" %}" class='btn btn-secondary btn-block'> 결제하기.</a>
                    <a href="/" class='btn btn-secondary btn-block'> 쇼핑 계속하기.</a>
                </div>
            </div>
        </div>
        <br>
    {% endif %}

{% endblock %}